// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzpvyNmjcGVDkE6z_5NXczjMb8re4amDU',
    appId: '1:408779212796:web:0a6941c22f22aa486ed479',
    messagingSenderId: '408779212796',
    projectId: 'carpool-service-1bd2e',
    authDomain: 'carpool-service-1bd2e.firebaseapp.com',
    storageBucket: 'carpool-service-1bd2e.appspot.com',
    measurementId: 'G-BYF624R2S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKjvtyFTOVB56ZZKhabwTjF8vCgBk5c0',
    appId: '1:408779212796:android:1d64e9994bfc885c6ed479',
    messagingSenderId: '408779212796',
    projectId: 'carpool-service-1bd2e',
    storageBucket: 'carpool-service-1bd2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bzK_zKnZZ9cav82XzrP78m06yn9zthg',
    appId: '1:408779212796:ios:0f971d7c6c0f47406ed479',
    messagingSenderId: '408779212796',
    projectId: 'carpool-service-1bd2e',
    storageBucket: 'carpool-service-1bd2e.appspot.com',
    iosBundleId: 'com.example.carpoolingService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bzK_zKnZZ9cav82XzrP78m06yn9zthg',
    appId: '1:408779212796:ios:163b8f39b77b048f6ed479',
    messagingSenderId: '408779212796',
    projectId: 'carpool-service-1bd2e',
    storageBucket: 'carpool-service-1bd2e.appspot.com',
    iosBundleId: 'com.example.carpoolingService.RunnerTests',
  );
}
